apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadev
  namespace: react-microk8s
  labels:
    name: webapp
#container spacefication 
spec: 
  replicas: 3
  selector: 
    matchLabels:
      name: webapp
  template:
    metadata:
      labels: 
        name:  webapp
  # image specification
  spec:
    containers:
      name: react-demo
      image: react
      imagePullPolicy: Always
      ports:
        containerPort: 80
